import { describe, expect, test } from "bun:test";
import fs from "node:fs";
import path from "node:path";
import {
  formatProjectReport,
  buildBook,
  computeWordCounts,
  createEntity,
  createStoryProject,
  exportManuscript,
  formatActionReport,
  migrateProject,
  projectReport,
  projectActions,
  reindexProject,
  removeEntity,
  renameEntity,
  scanProject,
  STORY_SCHEMA_VERSION,
  validateLinks,
  validateProject
} from "../src/story.js";
import { makeTempDir, writeMarkdown } from "./helpers.js";

function addStoryEntities(root) {
  writeMarkdown(path.join(root, "characters", "sera-voss.md"), `
name: "Sera Voss"
role: protagonist
status: alive
relationships:
  - character: kael-voss
    type: sibling
locations:
  - whispering-vale
`, "# Sera\n");
  writeMarkdown(path.join(root, "characters", "kael-voss.md"), `
name: "Kael Voss"
role: supporting
status: alive
relationships:
  - character: sera-voss
    type: sibling
locations:
  - whispering-vale
`, "# Kael\n");
  writeMarkdown(path.join(root, "worldbuilding", "locations", "whispering-vale.md"), `
name: "Whispering Vale"
type: wilderness
region: North
notable-characters:
  - sera-voss
  - kael-voss
`, "# Vale\n");
  writeMarkdown(path.join(root, "worldbuilding", "systems", "ember-magic.md"), `
name: "Ember Magic"
type: magic
`, "# Ember\n");
  writeMarkdown(path.join(root, "plot", "arcs", "reclamation.md"), `
name: "Reclamation"
type: main
status: planned
characters:
  - sera-voss
themes:
  - redemption
`, "# Arc\n");
  writeMarkdown(path.join(root, "chapters", "chapter-01.md"), `
title: "The Ember Wakes"
number: 1
pov: sera-voss
locations:
  - whispering-vale
characters:
  - sera-voss
arcs-advanced:
  - reclamation
status: draft
word-count: 0
`, "# Chapter 1\n\n## Outline\n\n1. Beat\n\n---\n\nSera returned home.");
  writeMarkdown(path.join(root, "scenes", "chapter-01-scene-01.md"), `
title: "Sera Returns"
chapter: chapter-01
scene: 1
pov: sera-voss
location: whispering-vale
characters:
  - sera-voss
arcs-advanced:
  - reclamation
status: draft
state-changes: []
`, "# Sera Returns\n");
}

describe("story project operations", () => {
  test("creates, scans, reindexes, counts, validates, links, and exports a story project", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({
      cwd,
      title: "The Last Ember",
      genre: "fantasy",
      subGenre: "epic",
      settingEra: "medieval",
      themes: ["redemption", "legacy"],
      pov: "third-person-limited",
      tense: "past",
      synopsis: "Sera returns.",
      force: false
    });

    expect(created.storyId).toBe("the-last-ember");
    expect(fs.existsSync(path.join(created.root, "story.md"))).toBe(true);
    expect(scanProject(created.root).story.data["schema-version"]).toBe(STORY_SCHEMA_VERSION);
    addStoryEntities(created.root);

    const project = scanProject(created.root);
    expect(project.characters.map((item) => item.id)).toEqual(["kael-voss", "sera-voss"]);
    expect(project.scenes.map((item) => item.id)).toEqual(["chapter-01-scene-01"]);
    expect(project.chapters[0].wordCount).toBe(3);

    const reindexed = reindexProject(created.root);
    expect(reindexed.changed.map((file) => path.basename(file))).toContain("_index.md");
    expect(fs.readFileSync(path.join(created.root, "characters", "_index.md"), "utf8")).toContain("[sera-voss](sera-voss.md)");
    expect(fs.readFileSync(path.join(created.root, "worldbuilding", "_index.md"), "utf8")).toContain("[whispering-vale](locations/whispering-vale.md)");
    expect(fs.readFileSync(path.join(created.root, "plot", "_index.md"), "utf8")).toContain("[reclamation](arcs/reclamation.md)");
    expect(fs.readFileSync(path.join(created.root, "scenes", "_index.md"), "utf8")).toContain("[chapter-01-scene-01](chapter-01-scene-01.md)");

    const counts = computeWordCounts(created.root, { write: true });
    expect(counts).toEqual({
      chapters: [{ number: 1, title: "The Ember Wakes", file: path.join("chapters", "chapter-01.md"), wordCount: 3 }],
      total: 3
    });
    expect(fs.readFileSync(path.join(created.root, "chapters", "chapter-01.md"), "utf8")).toContain("word-count: 3");

    expect(validateProject(created.root).ok).toBe(true);
    expect(validateLinks(created.root)).toEqual({ ok: true, errors: [], warnings: [] });

    const exported = exportManuscript(created.root, { out: "book.md" });
    expect(exported.chapters).toBe(1);
    expect(fs.readFileSync(exported.outFile, "utf8")).toContain("# Chapter 1: The Ember Wakes\n\nSera returned home.");

    const built = buildBook(created.root);
    expect(built).toEqual({
      outFile: path.join(created.root, "dist", "the-last-ember.md"),
      chapters: 1,
      format: "markdown"
    });
    expect(fs.readFileSync(built.outFile, "utf8")).toContain("Generated by story build");
  });

  test("builds a project report", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Reported Story", force: false });
    addStoryEntities(created.root);
    computeWordCounts(created.root, { write: true });

    const report = projectReport(created.root);
    expect(report.counts).toEqual({
      characters: 2,
      locations: 1,
      systems: 1,
      factions: 0,
      artifacts: 0,
      arcs: 1,
      chapters: 1,
      scenes: 1,
      questions: 0,
      promises: 0,
      glossaryTerms: 0,
      words: 3
    });
    expect(report.validation.ok).toBe(true);
    expect(report.links.ok).toBe(true);

    const formatted = formatProjectReport(report);
    expect(formatted).toContain("# Reported Story");
    expect(formatted).toContain(`Schema version: ${STORY_SCHEMA_VERSION}`);
    expect(formatted).toContain("- 1. The Ember Wakes (draft, 3 words, POV: sera-voss)");
    expect(formatted).toContain("- Validate: ok (0 errors, 0 warnings)");

    const empty = formatProjectReport(projectReport(createStoryProject({ cwd, title: "Empty Report", force: false }).root));
    expect(empty).toContain("Chapters:\n- None");
    expect(empty).toContain("Arcs:\n- None");
  });

  test("exports natural chapters without duplicating a leading H1 heading", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Harbor Example", force: false });
    writeMarkdown(path.join(created.root, "chapters", "chapter-01.md"), `
title: "The Tide Board"
number: 1
pov: ""
locations: []
characters: []
arcs-advanced: []
status: complete
word-count: 0
`, "# Chapter 1: The Tide Board\n\nProse starts here.");

    expect(scanProject(created.root).chapters[0].wordCount).toBe(3);

    const exported = exportManuscript(created.root, { out: "book.md" });
    const exportedText = fs.readFileSync(exported.outFile, "utf8");
    expect(exportedText.match(/^# Chapter 1: The Tide Board$/gm)?.length).toBe(1);
    expect(exportedText).toContain("# Chapter 1: The Tide Board\n\nProse starts here.");

    const built = buildBook(created.root);
    const builtText = fs.readFileSync(built.outFile, "utf8");
    expect(builtText.match(/^# Chapter 1: The Tide Board$/gm)?.length).toBe(1);
    expect(builtText).toContain("# Chapter 1: The Tide Board\n\nProse starts here.");
  });

  test("supports forced init, default metadata, and unchanged reindex", () => {
    const cwd = makeTempDir();
    const first = createStoryProject({ cwd, title: "Quiet Stars", force: false });
    expect(() => createStoryProject({ cwd, title: "Quiet Stars", force: false })).toThrow("already exists");
    const second = createStoryProject({ cwd, title: "Quiet Stars", force: true, themes: [] });
    expect(second.root).toBe(first.root);
    expect(reindexProject(second.root).changed).toEqual([]);
  });

  test("refuses to overwrite maintenance outputs through symlinks", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Symlink Trap", force: false });
    const outside = path.join(cwd, "outside.md");
    fs.writeFileSync(outside, "outside sentinel", "utf8");

    const chapterIndex = path.join(created.root, "chapters", "_index.md");
    fs.rmSync(chapterIndex);
    fs.symlinkSync(outside, chapterIndex);

    expect(() => reindexProject(created.root)).toThrow("Refusing to write through symlink");
    expect(fs.readFileSync(outside, "utf8")).toBe("outside sentinel");
  });

  test("refuses to write project files through symlinked directories", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Symlink Directory", force: false });
    const outsideChapters = path.join(cwd, "outside-chapters");
    fs.mkdirSync(outsideChapters);

    fs.rmSync(path.join(created.root, "chapters"), { recursive: true, force: true });
    fs.symlinkSync(outsideChapters, path.join(created.root, "chapters"), "dir");

    expect(() => createEntity(created.root, { kind: "chapter", name: "Escaped", number: 1 })).toThrow("symlinked project directory");
    expect(fs.existsSync(path.join(outsideChapters, "chapter-01.md"))).toBe(false);
  });

  test("refuses unsafe project directories reached during scans", () => {
    const cwd = makeTempDir();
    const fileDirectory = createStoryProject({ cwd, title: "File Directory", force: false });
    fs.rmSync(path.join(fileDirectory.root, "characters"), { recursive: true, force: true });
    fs.writeFileSync(path.join(fileDirectory.root, "characters"), "not a directory", "utf8");

    expect(() => scanProject(fileDirectory.root)).toThrow("Project path is not a directory");

    const escapedDirectory = createStoryProject({ cwd, title: "Escaped Directory", force: false });
    const outsideWorld = path.join(cwd, "outside-world");
    fs.mkdirSync(path.join(outsideWorld, "locations"), { recursive: true });
    fs.rmSync(path.join(escapedDirectory.root, "worldbuilding"), { recursive: true, force: true });
    fs.symlinkSync(outsideWorld, path.join(escapedDirectory.root, "worldbuilding"), "dir");

    expect(() => scanProject(escapedDirectory.root)).toThrow("project directory outside root");
  });

  test("rejects traversal ids before rename, remove, and scene creation", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Traversal IDs", force: false });
    const victim = path.join(cwd, "victim.md");
    fs.writeFileSync(victim, "victim sentinel", "utf8");

    expect(() => removeEntity(created.root, { kind: "character", id: "../../victim" })).toThrow("must be a kebab-case id");
    expect(() => renameEntity(created.root, { kind: "character", id: "../../victim", name: "Moved Victim" })).toThrow("must be a kebab-case id");
    expect(() => createEntity(created.root, { kind: "scene", name: "Escaped Scene", chapter: "../../victim" })).toThrow("chapter id must be a kebab-case id");
    expect(fs.readFileSync(victim, "utf8")).toBe("victim sentinel");
    expect(fs.existsSync(path.join(cwd, "victim-scene-01.md"))).toBe(false);
  });

  test("rejects relative export outputs outside the project root", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Output Traversal", force: false });
    addStoryEntities(created.root);

    expect(() => exportManuscript(created.root, { out: "../outside.md" })).toThrow("outside project root");
    expect(fs.existsSync(path.join(cwd, "outside.md"))).toBe(false);
  });

  test("rejects outputs through symlinked parent directories", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Output Symlink", force: false });
    addStoryEntities(created.root);
    const outsideDist = path.join(cwd, "outside-dist");
    fs.mkdirSync(outsideDist);
    fs.symlinkSync(outsideDist, path.join(created.root, "dist"), "dir");

    expect(() => buildBook(created.root)).toThrow("project path outside root");
    expect(fs.existsSync(path.join(outsideDist, "output-symlink.md"))).toBe(false);
  });

  test("recreates missing registry files without leaving the project root", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Missing Registry", force: false });
    const registry = path.join(created.root, "characters", "_index.md");
    fs.rmSync(registry);

    expect(reindexProject(created.root).changed).toContain(registry);
    expect(fs.readFileSync(registry, "utf8")).toContain("type: character-registry");
  });

  test("reports missing structure, frontmatter fields, registry warnings, word-count warnings, and link errors", () => {
    const cwd = makeTempDir();
    expect(validateProject(cwd).errors).toContain("Missing required path: story.md");

    const created = createStoryProject({ cwd, title: "Broken Links", force: false });
    writeMarkdown(path.join(created.root, "characters", "orphan.md"), `
name: Orphan
role: supporting
status: alive
relationships:
  - character: missing-person
    type: friend
locations:
  - missing-place
`, "# Orphan");
    writeMarkdown(path.join(created.root, "worldbuilding", "locations", "empty.md"), `
name: Empty
type: ruins
notable-characters:
  - missing-person
`, "# Empty");
    writeMarkdown(path.join(created.root, "plot", "arcs", "bad-arc.md"), `
name: Bad Arc
type: main
status: planned
characters:
  - missing-person
`, "# Arc");
    writeMarkdown(path.join(created.root, "chapters", "chapter-02.md"), `
title: "Bad Chapter"
number: 2
pov: orphan
locations:
  - missing-place
characters:
  - missing-person
arcs-advanced:
  - missing-arc
status: draft
word-count: 10
`, "## Chapter Text\n\nTwo words.");

    const validation = validateProject(created.root);
    expect(validation.ok).toBe(true);
    expect(validation.warnings.some((warning) => warning.includes("registry link"))).toBe(true);
    expect(validation.warnings.some((warning) => warning.includes("declares 10 words"))).toBe(true);

    const links = validateLinks(created.root);
    expect(links.ok).toBe(false);
    expect(links.errors.join("\n")).toContain("missing character missing-person");
    expect(links.errors.join("\n")).toContain("missing location missing-place");
    expect(links.errors.join("\n")).toContain("missing arc missing-arc");
  });

  test("reports missing backlinks and supports missing directories plus filename chapter numbers", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Backlink Gaps", force: false });
    fs.rmSync(path.join(created.root, "plot", "arcs"), { recursive: true, force: true });
    writeMarkdown(path.join(created.root, "characters", "sera-voss.md"), `
name: "Sera Voss"
role: protagonist
status: alive
relationships:
  - character: kael-voss
    type: sibling
locations:
  - whispering-vale
`, "# Sera");
    writeMarkdown(path.join(created.root, "characters", "kael-voss.md"), `
name: "Kael Voss"
role: supporting
status: alive
locations: []
`, "# Kael");
    writeMarkdown(path.join(created.root, "characters", "maren.md"), `
name: Maren
role: antagonist
status: alive
locations: []
`, "# Maren");
    writeMarkdown(path.join(created.root, "worldbuilding", "locations", "whispering-vale.md"), `
name: "Whispering Vale"
type: wilderness
notable-characters:
  - maren
`, "# Vale");
    writeMarkdown(path.join(created.root, "chapters", "chapter-07.md"), `
title: Seven
pov: sera-voss
locations: []
characters: []
arcs-advanced: []
status: draft
word-count: 0
`, "## Chapter Text\n\nSeven words here.");

    const project = scanProject(created.root);
    expect(project.arcs).toEqual([]);
    expect(project.chapters[0].number).toBe(7);

    const links = validateLinks(created.root);
    expect(links.errors.join("\n")).toContain("relationship to kael-voss is missing backlink");
    expect(links.errors.join("\n")).toContain("location whispering-vale is missing notable-character backlink");
    expect(links.errors.join("\n")).toContain("notable character maren is missing location backlink");
  });

  test("sorts multiple chapters by number and then filename", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Chapter Order", force: false });
    writeMarkdown(path.join(created.root, "chapters", "chapter-10.md"), `
title: Ten
number: 10
pov: ""
locations: []
characters: []
arcs-advanced: []
status: draft
word-count: 0
`, "## Chapter Text\n\nTen.");
    writeMarkdown(path.join(created.root, "chapters", "chapter-02.md"), `
title: Two
number: 2
pov: ""
locations: []
characters: []
arcs-advanced: []
status: draft
word-count: 0
`, "## Chapter Text\n\nTwo.");

    expect(scanProject(created.root).chapters.map((chapter) => chapter.number)).toEqual([2, 10]);
  });

  test("reports missing required frontmatter fields and empty export", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "No Chapters", force: false });
    writeMarkdown(path.join(created.root, "characters", "nameless.md"), `
name: Nameless
role: supporting
`, "# Nameless");

    const validation = validateProject(created.root);
    expect(validation.ok).toBe(false);
    expect(validation.errors).toContain(`characters${path.sep}nameless.md is missing frontmatter field status`);
    expect(() => exportManuscript(created.root)).toThrow("No chapters found to export");
  });

  test("reports schema and frontmatter contract violations", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Strict Format", force: false });
    fs.writeFileSync(
      path.join(created.root, "story.md"),
      fs.readFileSync(path.join(created.root, "story.md"), "utf8")
        .replace("schema-version: 1", "schema-version: 99")
        .replace("schema-version: 2", "schema-version: 99")
        .replace("genre: fiction", "genre:\n  - fiction")
        .replace("themes:\n  - change", "themes: none")
        .replace("status: planning", "status: unknown-stage"),
      "utf8"
    );
    fs.writeFileSync(
      path.join(created.root, "characters", "_index.md"),
      fs.readFileSync(path.join(created.root, "characters", "_index.md"), "utf8")
        .replace("type: character-registry", "type: wrong-registry")
        .replace("story: strict-format", "story: wrong-story"),
      "utf8"
    );
    writeMarkdown(path.join(created.root, "characters", "Bad Name.md"), `
name:
  - Bad Name
role: cameo
status: alive
aliases:
  - ""
relationships:
  - character: Not Kebab
    type: parent
  - not-object
  - type: friend
  - character: missing-person
locations: none
`, "# Bad");
    writeMarkdown(path.join(created.root, "characters", "parent-one.md"), `
name: Parent One
role: supporting
status: alive
relationships:
  - character: child-one
    type: parent
locations: []
`, "# Parent");
    writeMarkdown(path.join(created.root, "characters", "child-one.md"), `
name: Child One
role: supporting
status: alive
relationships:
  - character: parent-one
    type: parent
locations: []
`, "# Child");
    writeMarkdown(path.join(created.root, "characters", "bad-relationships.md"), `
name: Bad Relationships
role: supporting
status: alive
relationships: none
locations: []
`, "# Bad Relationships");
    writeMarkdown(path.join(created.root, "worldbuilding", "systems", "bad-system.md"), `
name: Bad System
type: technology
prevalence:
  - common
`, "# Bad System");
    writeMarkdown(path.join(created.root, "chapters", "chapter-01.md"), `
title: One
number: 2
pov: missing-person
locations: []
characters: []
arcs-advanced: []
status: invalid
word-count: many
`, "## Chapter Text\n\nWords.");
    writeMarkdown(path.join(created.root, "chapters", "chapter-00.md"), `
title: Zero
number: 0
pov: ""
locations: []
characters: []
arcs-advanced: []
status: draft
word-count: 1
`, "## Chapter Text\n\nZero.");
    writeMarkdown(path.join(created.root, "chapters", "chapter-02.md"), `
title: Two
number: 2
pov: ""
locations: []
characters: []
arcs-advanced: []
status: draft
word-count: 1
`, "## Chapter Text\n\nTwo.");

    const validation = validateProject(created.root);
    expect(validation.ok).toBe(false);
    expect(validation.errors.join("\n")).toContain(`story.md schema-version must be ${STORY_SCHEMA_VERSION}`);
    expect(validation.errors.join("\n")).toContain("story.md frontmatter field genre must be a scalar");
    expect(validation.errors.join("\n")).toContain("story.md frontmatter field themes must be a list");
    expect(validation.errors.join("\n")).toContain("story.md frontmatter field status has unsupported value unknown-stage");
    expect(validation.errors.join("\n")).toContain("characters/_index.md type must be character-registry");
    expect(validation.errors.join("\n")).toContain("characters/_index.md story must be strict-format");
    expect(validation.errors.join("\n")).toContain("characters/Bad Name.md filename id must be kebab-case");
    expect(validation.errors.join("\n")).toContain("characters/Bad Name.md frontmatter field name must be a scalar");
    expect(validation.errors.join("\n")).toContain("characters/Bad Name.md frontmatter field role has unsupported value cameo");
    expect(validation.errors.join("\n")).toContain("characters/Bad Name.md frontmatter field aliases must contain only non-empty strings");
    expect(validation.errors.join("\n")).toContain("characters/Bad Name.md frontmatter field locations must be a list");
    expect(validation.errors.join("\n")).toContain("characters/Bad Name.md relationship character Not Kebab must be kebab-case");
    expect(validation.errors.join("\n")).toContain("characters/Bad Name.md frontmatter field relationships must contain objects");
    expect(validation.errors.join("\n")).toContain("characters/Bad Name.md relationship is missing character");
    expect(validation.errors.join("\n")).toContain("characters/Bad Name.md relationship to missing-person is missing type");
    expect(validation.errors.join("\n")).toContain("characters/bad-relationships.md frontmatter field relationships must be a list");
    expect(validation.errors.join("\n")).toContain("worldbuilding/systems/bad-system.md frontmatter field prevalence must be a scalar");
    expect(validation.errors.join("\n")).toContain("chapters/chapter-00.md filename must match chapter-{NN}.md");
    expect(validation.errors.join("\n")).toContain("chapters/chapter-00.md number must be greater than 0");
    expect(validation.errors.join("\n")).toContain("chapters/chapter-01.md frontmatter field status has unsupported value invalid");
    expect(validation.errors.join("\n")).toContain("chapters/chapter-01.md frontmatter field word-count must be an integer");
    expect(validation.errors.join("\n")).toContain("chapters/chapter-01.md number must match filename chapter number 1");
    expect(validation.errors.join("\n")).toContain("chapters/chapter-02.md duplicates chapter number 2");

    const links = validateLinks(created.root);
    expect(links.errors.join("\n")).toContain("references missing POV character missing-person");
    expect(links.errors.join("\n")).toContain("relationship parent to child-one expects backlink type child, got parent");
  });

  test("creates, renames, removes, migrates, and recommends next actions", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Helper Story", force: false });
    const character = createEntity(created.root, { kind: "character", name: "Mira Sol", role: "protagonist" });
    const location = createEntity(created.root, { kind: "location", name: "Glass Harbor", type: "city", character: "mira-sol" });
    const system = createEntity(created.root, { kind: "system", name: "Tide Magic", type: "magic" });
    const faction = createEntity(created.root, { kind: "faction", name: "Harbor Guild", type: "guild", member: "mira-sol", location: "glass-harbor" });
    const artifact = createEntity(created.root, { kind: "artifact", name: "Tide Key", owner: "harbor-guild", location: "glass-harbor" });
    const arc = createEntity(created.root, { kind: "arc", name: "Find The Tide Key", type: "main", character: "mira-sol" });
    const chapter = createEntity(created.root, { kind: "chapter", name: "Arrival", number: 1, pov: "mira-sol", location: "glass-harbor", character: "mira-sol", arc: "find-the-tide-key" });
    const scene = createEntity(created.root, { kind: "scene", name: "At The Pier", chapter: "chapter-01", scene: 1, pov: "mira-sol", location: "glass-harbor", character: "mira-sol", arc: "find-the-tide-key" });
    const nextScene = createEntity(created.root, { kind: "scene", name: "Second Beat", chapter: "chapter-01" });
    const question = createEntity(created.root, { kind: "question", name: "Who hid the key?", introduced: "chapter-01", character: "mira-sol" });
    const promise = createEntity(created.root, { kind: "promise", name: "The key opens the reef vault", planted: "chapter-01", arc: "find-the-tide-key", character: "mira-sol" });
    const term = createEntity(created.root, { kind: "term", name: "Reef Vault", category: "place", alias: "vault" });

    expect(character.id).toBe("mira-sol");
    expect(location.id).toBe("glass-harbor");
    expect(system.id).toBe("tide-magic");
    expect(faction.id).toBe("harbor-guild");
    expect(artifact.id).toBe("tide-key");
    expect(arc.id).toBe("find-the-tide-key");
    expect(chapter.id).toBe("chapter-01");
    expect(scene.id).toBe("chapter-01-scene-01");
    expect(nextScene.id).toBe("chapter-01-scene-02");
    expect(question.id).toBe("who-hid-the-key");
    expect(promise.id).toBe("the-key-opens-the-reef-vault");
    expect(term.id).toBe("reef-vault");
    const activeActions = formatActionReport(projectActions(created.root));
    expect(activeActions).toContain("Track open questions");
    expect(activeActions).toContain("Review promises and payoffs");

    const renamed = renameEntity(created.root, { kind: "character", id: "mira-sol", name: "Mira Vale" });
    expect(renamed.id).toBe("mira-vale");
    expect(fs.readFileSync(path.join(created.root, "chapters", "chapter-01.md"), "utf8")).toContain("mira-vale");

    const removed = removeEntity(created.root, { kind: "promise", id: "the-key-opens-the-reef-vault" });
    expect(removed.id).toBe("the-key-opens-the-reef-vault");
    expect(fs.existsSync(path.join(created.root, "continuity", "promises", "the-key-opens-the-reef-vault.md"))).toBe(false);

    const actions = projectActions(created.root);
    expect(formatActionReport(actions)).toContain("Draft chapter 2");
    expect(formatActionReport({
      title: "Empty",
      validation: { ok: true, errors: [], warnings: [] },
      links: { ok: true, errors: [], warnings: [] },
      continuity: { ok: true, errors: [], warnings: [] },
      actions: []
    })).toContain("No actions found");

    fs.rmSync(path.join(created.root, "glossary"), { recursive: true, force: true });
    fs.writeFileSync(
      path.join(created.root, "story.md"),
      fs.readFileSync(path.join(created.root, "story.md"), "utf8").replace("schema-version: 2", "schema-version: 1"),
      "utf8"
    );
    const migrated = migrateProject(created.root);
    expect(migrated.changed.length).toBeGreaterThan(0);
    expect(scanProject(created.root).story.data["schema-version"]).toBe(STORY_SCHEMA_VERSION);
  });

  test("remove scrubs references without rewriting untouched files", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Remove Touch", force: false });
    createEntity(created.root, { kind: "character", name: "Keeper", role: "supporting" });
    createEntity(created.root, { kind: "promise", name: "Old Setup", character: "keeper" });
    const storyPath = path.join(created.root, "story.md");
    fs.writeFileSync(storyPath, fs.readFileSync(storyPath, "utf8").replace("title:", "# hand-written note\ntitle:"), "utf8");
    const annotated = fs.readFileSync(storyPath, "utf8");

    removeEntity(created.root, { kind: "character", id: "keeper" });

    expect(fs.readFileSync(storyPath, "utf8")).toBe(annotated);
    expect(fs.readFileSync(path.join(created.root, "continuity", "promises", "old-setup.md"), "utf8")).not.toContain("keeper");
  });

  test("rename leaves overlapping entity ids and prose words intact", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Rename Overlap", force: false });
    createEntity(created.root, { kind: "character", name: "Mara", role: "protagonist" });
    createEntity(created.root, { kind: "character", name: "Mara Quill", role: "supporting" });
    createEntity(created.root, { kind: "chapter", name: "Arrival", number: 1, pov: "mara-quill", character: "mara-quill,mara" });
    const chapterPath = path.join(created.root, "chapters", "chapter-01.md");
    fs.appendFileSync(chapterPath, "The marathon passed mara on the docks.\n", "utf8");

    renameEntity(created.root, { kind: "character", id: "mara", name: "Tess" });

    const chapterText = fs.readFileSync(chapterPath, "utf8");
    expect(chapterText).toContain("pov: mara-quill");
    expect(chapterText).toContain("- tess");
    expect(chapterText).toContain("The marathon passed tess on the docks.");
    expect(fs.existsSync(path.join(created.root, "characters", "mara-quill.md"))).toBe(true);
    expect(validateLinks(created.root)).toEqual({ ok: true, errors: [], warnings: [] });
  });

  test("covers helper errors, fallback branches, and malformed continuity state", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Coverage Branches", force: false });
    expect(() => createEntity(created.root, { kind: "character", name: "" })).toThrow("name is required");
    expect(() => createEntity(created.root, { kind: "beast", name: "Wolf" })).toThrow("Unsupported entity kind");
    createEntity(created.root, { kind: "glossary", name: "Moon Gate" });
    createEntity(created.root, { kind: "character", name: "Branch Person", location: "missing-location" });
    createEntity(created.root, { kind: "location", name: "Branch Place", character: "missing-person" });
    expect(() => createEntity(created.root, { kind: "location", name: "Branch Place" })).toThrow("already exists");
    expect(() => renameEntity(created.root, { kind: "character", id: "", name: "Nope" })).toThrow("rename requires");
    expect(() => renameEntity(created.root, { kind: "character", id: "missing-person", name: "Nope" })).toThrow("does not exist");
    createEntity(created.root, { kind: "character", name: "Other Person" });
    expect(() => renameEntity(created.root, { kind: "character", id: "branch-person", name: "Other Person" })).toThrow("already exists");
    expect(() => removeEntity(created.root, { kind: "character", id: "" })).toThrow("remove requires");
    expect(() => removeEntity(created.root, { kind: "character", id: "missing-person" })).toThrow("does not exist");
    expect(() => buildBook(created.root, { format: "epub" })).toThrow("No chapters found to export");
    writeMarkdown(path.join(created.root, "chapters", "chapter-01.md"), `
title: Stale
number: 1
pov: ""
locations: []
characters: []
arcs-advanced: []
status: draft
word-count: 99
`, "## Chapter Text\n\nOne.");
    writeMarkdown(path.join(created.root, "scenes", "chapter-01-scene-01.md"), `
title: Optional State
chapter: chapter-01
scene: 1
status: draft
`, "# Optional State");
    expect(createEntity(created.root, { kind: "chapter", name: "Auto Numbered" }).id).toBe("chapter-02");
    expect(formatActionReport(projectActions(created.root))).toContain("Refresh word counts");

    fs.writeFileSync(
      path.join(created.root, "continuity", "state.md"),
      fs.readFileSync(path.join(created.root, "continuity", "state.md"), "utf8")
        .replace("type: continuity-state", "type: wrong-state")
        .replace("story: coverage-branches", "story: wrong-story")
        .replace("character-state: []", "character-state: none"),
      "utf8"
    );
    writeMarkdown(path.join(created.root, "scenes", "bad-state.md"), `
title: Bad State
chapter: chapter-01
scene: 1
status: draft
state-changes: none
`, "# Bad State");

    const validation = validateProject(created.root);
    expect(validation.errors.join("\n")).toContain("continuity/state.md type must be continuity-state");
    expect(validation.errors.join("\n")).toContain("continuity/state.md story must be coverage-branches");
    expect(validation.errors.join("\n")).toContain("continuity/state.md frontmatter field character-state must be a list");
    expect(validation.errors.join("\n")).toContain("scenes/bad-state.md frontmatter field state-changes must be a list");

    const actions = formatActionReport(projectActions(created.root));
    expect(actions).toContain("Fix validation errors");
    expect(actions).toContain("Fix broken references");
  });

  test("validates v2 entity frontmatter and reference contracts", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "V2 Broken", force: false });
    writeMarkdown(path.join(created.root, "worldbuilding", "factions", "bad-faction.md"), `
name: Bad Faction
type: guild
status: active
members:
  - missing-person
locations:
  - missing-place
tags: []
`, "# Bad Faction");
    writeMarkdown(path.join(created.root, "worldbuilding", "artifacts", "bad-artifact.md"), `
name: Bad Artifact
type: relic
status: active
owner: missing-owner
location: missing-place
tags: []
`, "# Bad Artifact");
    writeMarkdown(path.join(created.root, "chapters", "chapter-01.md"), `
title: One
number: 1
pov: ""
locations: []
characters: []
arcs-advanced: []
status: draft
word-count: 1
`, "## Chapter Text\n\nOne.");
    writeMarkdown(path.join(created.root, "scenes", "bad-scene.md"), `
title: Bad Scene
chapter: missing-chapter
scene: 0
pov: missing-person
location: missing-place
characters:
  - missing-person
arcs-advanced:
  - missing-arc
status: invalid
state-changes:
  - not-object
`, "# Bad Scene");
    writeMarkdown(path.join(created.root, "continuity", "questions", "bad-question.md"), `
title: Bad Question
status: invalid
introduced: missing-chapter
resolved: missing-chapter
characters:
  - missing-person
`, "# Bad Question");
    writeMarkdown(path.join(created.root, "continuity", "promises", "bad-promise.md"), `
title: Bad Promise
status: invalid
planted: missing-chapter
payoff: missing-chapter
arcs:
  - missing-arc
characters:
  - missing-person
`, "# Bad Promise");
    writeMarkdown(path.join(created.root, "glossary", "terms", "bad-term.md"), `
term: Bad Term
category: invalid
aliases:
  - ""
`, "# Bad Term");

    const validation = validateProject(created.root);
    expect(validation.ok).toBe(false);
    expect(validation.errors.join("\n")).toContain("scenes/bad-scene.md frontmatter field status has unsupported value invalid");
    expect(validation.errors.join("\n")).toContain("scenes/bad-scene.md scene must be greater than 0");
    expect(validation.errors.join("\n")).toContain("continuity/questions/bad-question.md frontmatter field status has unsupported value invalid");
    expect(validation.errors.join("\n")).toContain("continuity/promises/bad-promise.md frontmatter field status has unsupported value invalid");
    expect(validation.errors.join("\n")).toContain("glossary/terms/bad-term.md frontmatter field category has unsupported value invalid");

    const links = validateLinks(created.root);
    expect(links.ok).toBe(false);
    expect(links.errors.join("\n")).toContain("bad-faction.md references missing member missing-person");
    expect(links.errors.join("\n")).toContain("bad-artifact.md references missing owner missing-owner");
    expect(links.errors.join("\n")).toContain("bad-scene.md references missing chapter missing-chapter");
    expect(links.errors.join("\n")).toContain("bad-question.md references missing character missing-person");
    expect(links.errors.join("\n")).toContain("bad-promise.md references missing arc missing-arc");
  });

  test("reports numeric scene chapter ids as link errors instead of crashing scans", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Numeric Chapter", force: false });
    const chapters = ["chapter-02", "3", "chapter-01", "chapter-04", "chapter-03"];
    chapters.forEach((chapter, index) => {
      writeMarkdown(path.join(created.root, "scenes", `${String.fromCharCode(97 + index)}-scene.md`), `
title: Scene ${index + 1}
chapter: ${chapter}
scene: 1
status: draft
`, `# Scene ${index + 1}`);
    });

    const links = validateLinks(created.root);
    expect(links.ok).toBe(false);
    expect(links.errors.join("\n")).toContain("scenes/b-scene.md references missing chapter 3");
  });

  test("builds epub and docx formats and rejects unknown formats", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Plain Build", force: false });
    writeMarkdown(path.join(created.root, "chapters", "chapter-01.md"), `
title: One
number: 1
pov: ""
locations: []
characters: []
arcs-advanced: []
status: draft
word-count: 0
`, "## Chapter Text\n\nOne.\n\n---\n\nTwo.");

    const epub = buildBook(created.root, { format: "epub" });
    const docx = buildBook(created.root, { format: "docx" });
    expect(epub).toEqual({
      outFile: path.join(created.root, "dist", "plain-build.epub"),
      chapters: 1,
      format: "epub"
    });
    expect(docx).toEqual({
      outFile: path.join(created.root, "dist", "plain-build.docx"),
      chapters: 1,
      format: "docx"
    });
    expect(fs.readFileSync(epub.outFile).readUInt32LE(0)).toBe(0x04034b50);
    expect(fs.readFileSync(epub.outFile).toString("utf8")).toContain("dcterms:modified");
    expect(fs.readFileSync(epub.outFile).toString("utf8")).toContain("<p>* * *</p>");
    expect(fs.readFileSync(docx.outFile).toString("utf8")).toContain("word/document.xml");
    expect(fs.readFileSync(docx.outFile).toString("utf8")).toContain("word/styles.xml");
    expect(fs.readFileSync(docx.outFile).toString("utf8")).toContain("<w:t>* * *</w:t>");
    expect(() => buildBook(created.root, { format: "pdf" })).toThrow("Unsupported build format: pdf");
  });
});
