import { createTool } from '@mastra/core/tools';
import { z } from 'zod';
import path from 'node:path';
import fs from 'node:fs/promises';
import { okResult, errorResult } from './video-types.js';
import { runVideoScript, ensureVideoProjectStructure, VIDEO_ENGINE_ROOT } from './video-runner.js';

export const videoYoutubeUploadTool = createTool({
  id: 'video_youtube_upload',
  description:
    'Prepares and executes upload of a finished video to YouTube (as private/unlisted draft or scheduled). REQUIRES USER APPROVAL before triggering live upload.',
  inputSchema: z.object({
    projectFolder: z.string().describe('Project identifier, e.g. "video-1"'),
    videoFilePath: z.string().describe('Absolute or relative path to finished MP4 file'),
    thumbnailPath: z.string().optional().describe('Path to JPG thumbnail file'),
    privacyStatus: z.enum(['private', 'unlisted', 'public']).default('private').describe('YouTube privacy status'),
    dryRun: z.boolean().default(true).describe('If true, validates plan without calling YouTube API'),
  }),
  execute: async (context) => {
    try {
      const { projectPath, packagingDir } = await ensureVideoProjectStructure(context.projectFolder);
      const metaPath = path.join(packagingDir, 'metadata.json');

      let metaData: { title?: string; description?: string; tags?: string[] } = {};
      try {
        metaData = JSON.parse(await fs.readFile(metaPath, 'utf-8'));
      } catch {
        metaData = {
          title: `SPLOT OS Episode — ${context.projectFolder}`,
          description: 'Autonomous Agentic Architecture video generated by SPLOT OS.',
          tags: ['SPLOT OS', 'AI Agents', 'Mastra', 'TypeScript'],
        };
      }

      // Prepare publish.json plan
      const publishPlan = {
        title: metaData.title,
        description: metaData.description,
        tags: metaData.tags || [],
        privacy: context.privacyStatus,
        video: context.videoFilePath,
        thumbnail: context.thumbnailPath || path.join(packagingDir, 'thumbs', 'thumbnail_A.jpg'),
        categoryId: 28, // Science & Technology
      };

      const planPath = path.join(packagingDir, 'publish.json');
      await fs.writeFile(planPath, JSON.stringify(publishPlan, null, 2), 'utf-8');

      const args = ['upload', planPath];
      if (context.dryRun) {
        args.push('--dry-run');
      }

      const output = await runVideoScript('yt_upload.py', args);

      return okResult({
        projectFolder: context.projectFolder,
        planPath,
        dryRun: context.dryRun,
        privacy: context.privacyStatus,
        title: publishPlan.title,
        logs: output.stdout,
      });
    } catch (err) {
      return errorResult(err);
    }
  },
});
