#!/usr/bin/env tsx
/**
 * build:agent-board — Etap 2 (IDEALSYSTEMMASTERPLAN A1).
 *
 * Assembles the Agent Board from three sources:
 *   1. static cards        — config/agent-board.ts (hand-edited, source of truth)
 *   2. model assignment    — config/model-manifest.ts (never duplicated in cards)
 *   3. track record        — Mongo agent_events via dashboard-stats (30d window)
 *
 * Outputs:
 *   - Mongo `agent_board` (one doc per agent: card + model + trackRecord)
 *   - src/mastra/prompts/meta/_generated/roster.md (compact roster included
 *     by prompts/meta/base.md via {{include:_generated/roster.md}})
 *
 * Fail-safe: when Mongo is unreachable the roster is still generated from the
 * static cards (without track records) so `mastra build` never blocks on infra.
 *
 * Refresh: weekly via cron-runner + manually via `npm run build:agent-board`.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { agentBoard, type AgentCard } from '../config/agent-board.js';
import { agentModels } from '../config/model-manifest.js';

export type TrackRecord = {
  totalTasks: number;
  successRate: number;
  avgCostUsd: number;
  avgLatencyMs: number;
  windowDays: number;
};

export type AgentBoardDoc = AgentCard & {
  model?: string;
  trackRecord?: TrackRecord;
  updatedAt: Date;
};

const ROSTER_PATH = path.resolve('src/mastra/prompts/meta/_generated/roster.md');
const WINDOW_DAYS = 30;

async function loadTrackRecords(): Promise<Map<string, TrackRecord>> {
  const records = new Map<string, TrackRecord>();
  try {
    const { buildWindow, getAgentSuccessRates } = await import('../services/dashboard-stats.js');
    const stats = await getAgentSuccessRates(buildWindow(`${WINDOW_DAYS}d`));
    for (const s of stats) {
      if (s.totalTasks === 0) continue;
      records.set(s.agentId, {
        totalTasks: s.totalTasks,
        successRate: Math.round(s.successRate * 1000) / 1000,
        avgCostUsd: s.totalTasks > 0 ? Math.round((s.costUsd / s.totalTasks) * 10000) / 10000 : 0,
        avgLatencyMs: s.avgLatencyMs,
        windowDays: WINDOW_DAYS,
      });
    }
  } catch (err) {
    console.warn('[AgentBoard] Mongo unavailable — roster without track records:', (err as Error).message);
  }
  return records;
}

function trackLine(t: TrackRecord | undefined): string {
  if (!t) return 'track: no data';
  const latency = t.avgLatencyMs >= 60_000
    ? `~${Math.round(t.avgLatencyMs / 60_000)}min`
    : `~${Math.round(t.avgLatencyMs / 1000)}s`;
  return `track: ${(t.successRate * 100).toFixed(0)}% ok, ~$${t.avgCostUsd.toFixed(3)}, ${latency} (${t.totalTasks}×${t.windowDays}d)`;
}

export function renderRosterLine(card: AgentCard, model: string | undefined, track: TrackRecord | undefined): string {
  const use = card.whenToUse[0] ?? '';
  const notUse = card.whenNotToUse[0] ?? '';
  return [
    `- **${card.id}** · ${card.outputArtifacts.join('/')} · ${card.delegation} · ${card.costClass}/${card.latencyClass}`,
    `  ${card.oneLiner}`,
    `  use: ${use} | not: ${notUse} | ${trackLine(track)}${model ? ` | model: ${model}` : ''}`,
  ].join('\n');
}

export function renderRoster(tracks: Map<string, TrackRecord>): string {
  const models = agentModels as Record<string, string>;
  // Internal helpers are deliberately absent: meta may not delegate to them, so
  // an entry here is prompt budget spent on a forbidden route. They remain on the
  // board, delegable by their owning agent, and reachable via `agent_board_get`.
  const lines = Object.values(agentBoard)
    .filter((card) => !card.internal)
    .map((card) => renderRosterLine(card, models[card.id], tracks.get(card.id)));
  return [
    '<!-- GENERATED by scripts/build-agent-board.ts — DO NOT EDIT.',
    `     Source: config/agent-board.ts + model-manifest + agent_events (${WINDOW_DAYS}d). -->`,
    '',
    '## Agent roster (generated)',
    '',
    'One entry per delegable agent: `id · artifacts · delegation · cost/latency`.',
    'Before delegating anything non-obvious: `agent_board_get(agentId)` → full card',
    'with input contract, examples, hard rules, and track record. Choose by data.',
    'Domain helpers (reviewers, the n8n MCP engineer) are not listed: their owning',
    'agent calls them, never you. `agent_board_get` still describes them.',
    '',
    ...lines,
    '',
  ].join('\n');
}

async function persistToMongo(tracks: Map<string, TrackRecord>): Promise<boolean> {
  try {
    const { getDb } = await import('../lib/mongo.js');
    const db = await getDb();
    const col = db.collection<AgentBoardDoc>('agent_board');
    const models = agentModels as Record<string, string>;
    const now = new Date();
    for (const card of Object.values(agentBoard)) {
      const doc: AgentBoardDoc = {
        ...card,
        model: models[card.id],
        trackRecord: tracks.get(card.id),
        updatedAt: now,
      };
      await col.updateOne({ id: card.id }, { $set: doc }, { upsert: true });
    }
    // Remove cards for agents no longer on the board
    await col.deleteMany({ id: { $nin: Object.keys(agentBoard) } });
    return true;
  } catch (err) {
    console.warn('[AgentBoard] Mongo persist skipped:', (err as Error).message);
    return false;
  }
}

export async function buildAgentBoard(): Promise<{ mongoOk: boolean; rosterPath: string }> {
  const tracks = await loadTrackRecords();
  const roster = renderRoster(tracks);
  mkdirSync(path.dirname(ROSTER_PATH), { recursive: true });
  writeFileSync(ROSTER_PATH, roster);
  const mongoOk = await persistToMongo(tracks);
  return { mongoOk, rosterPath: ROSTER_PATH };
}

// CLI entry
const isMain = process.argv[1]?.endsWith('build-agent-board.ts');
if (isMain) {
  buildAgentBoard()
    .then(({ mongoOk, rosterPath }) => {
      console.log(`✅ Agent Board built: ${Object.keys(agentBoard).length} cards → ${rosterPath}` +
        ` | Mongo agent_board: ${mongoOk ? 'updated' : 'SKIPPED (offline)'}`);
      process.exit(0);
    })
    .catch((err) => {
      console.error('❌ build:agent-board failed:', err);
      process.exit(1);
    });
}
