#!/usr/bin/env tsx
/**
 * check:agent-board-sync — Etap 2 (IDEALSYSTEMMASTERPLAN).
 *
 * Fails on drift between the Agent Board and reality:
 *   1. every board card corresponds to an agent registered in index.ts;
 *   2. delegate-task derives its enum from AGENT_BOARD_IDS (no hand-kept list);
 *   3. delegate-task's internal AGENT_IDS registry matches the board exactly;
 *   4. prompts/meta/base.md includes the generated roster;
 *   5. the generated roster is in sync with the cards (every id present;
 *      regenerated content structure matches);
 *   6. loadPrompt('meta/base') resolves the include (no missing marker);
 *   7. board tools are registered on meta and all domain orchestrators.
 */
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { agentBoard, AGENT_BOARD_IDS } from '../config/agent-board.js';
import { agentModels } from '../config/model-manifest.js';
import { loadPrompt } from '../lib/prompt-loader.js';

let failures = 0;
function check(name: string, fn: () => void | Promise<void>): Promise<void> {
  return Promise.resolve().then(fn)
    .then(() => console.log(`  ✓ ${name}`))
    .catch((err) => { failures += 1; console.error(`  ✗ ${name}: ${(err as Error).message}`); });
}

const indexSource = readFileSync('src/mastra/index.ts', 'utf8');
const delegateSource = readFileSync('src/mastra/tools/system/delegate-task.ts', 'utf8');
const basePrompt = readFileSync('src/mastra/prompts/meta/base.md', 'utf8');
const rosterSource = readFileSync('src/mastra/prompts/meta/_generated/roster.md', 'utf8');

async function main() {
  console.log('check:agent-board-sync');

  await check('every board card is a registered agent in index.ts', () => {
    const agentsBlock = indexSource.match(/agents: \{([\s\S]*?)\},\n\s*scorers:/)?.[1] ?? '';
    for (const id of AGENT_BOARD_IDS) {
      assert.ok(new RegExp(`\\b${id}\\b`).test(agentsBlock), `${id} has a card but is not registered in index.ts`);
    }
  });

  await check('delegate-task enum derives from AGENT_BOARD_IDS', () => {
    assert.ok(delegateSource.includes('z.enum(AGENT_BOARD_IDS)'),
      'delegate-task must use z.enum(AGENT_BOARD_IDS), not a hand-kept list');
  });

  await check('delegate-task AGENT_IDS registry matches board exactly', async () => {
    const { AGENT_SOURCE_REGISTRY } = await import('../config/agent-source-registry.js');
    for (const id of AGENT_BOARD_IDS) {
      assert.ok(id in AGENT_SOURCE_REGISTRY, `${id} from board must be present in AGENT_SOURCE_REGISTRY`);
    }
  });

  await check('base.md includes generated roster (not a hand-kept table)', () => {
    assert.ok(basePrompt.includes('{{include:_generated/roster.md}}'), 'missing include directive');
    assert.ok(!basePrompt.includes('| `marketingAgent` |'), 'old hand-kept roster table still present');
  });

  await check('generated roster lists every DELEGABLE board id, and no internal helper', () => {
    for (const id of AGENT_BOARD_IDS) {
      const card = agentBoard[id]!;
      if (card.internal) {
        // Meta may not delegate to these, so a roster entry is prompt budget
        // spent on a forbidden route — and the budget is enforced.
        assert.ok(!rosterSource.includes(`**${id}**`),
          `${id} is an internal helper and must NOT appear in meta's roster`);
        continue;
      }
      assert.ok(rosterSource.includes(`**${id}**`),
        `${id} missing from roster.md — run npm run build:agent-board`);
    }
    assert.ok(rosterSource.includes('GENERATED by scripts/build-agent-board.ts'),
      'roster.md must keep its generation marker');
  });

await check('loadPrompt resolves the roster include', async () => {
    const loaded = await loadPrompt('meta/base');
    assert.ok(!loaded.includes('{{include:'), 'unresolved include directive in loaded prompt');
    assert.ok(!loaded.includes('include missing'), 'roster include failed to resolve');
    assert.ok(loaded.includes('## Agent roster (generated)'), 'roster content not inlined');
  });

  await check('every board agent has a model assignment', () => {
    const models = agentModels as Record<string, string>;
    for (const id of AGENT_BOARD_IDS) {
      assert.ok(models[id], `${id} missing from model-manifest agentModels`);
    }
  });

  await check('board tools registered on meta + domain orchestrators', () => {
    const orchestrators = [
      'meta-agent', 'chef-agent', 'hunt-agent', 'content-agent',
      'writer-agent', 'film-agent', 'musician-agent', 'automation-architect',
    ];
    for (const file of orchestrators) {
      const src = readFileSync(`src/mastra/agents/${file}.ts`, 'utf8');
      assert.ok(src.includes('agentBoardListTool') && src.includes('agentBoardGetTool'),
        `${file}.ts does not register agent board tools`);
    }
  });

  await check('cards are complete (whenToUse, whenNotToUse, contract, example)', () => {
    for (const card of Object.values(agentBoard)) {
      assert.ok(card.oneLiner.length > 10, `${card.id}: oneLiner too short`);
      assert.ok(card.whenToUse.length >= 1, `${card.id}: whenToUse empty`);
      assert.ok(card.whenNotToUse.length >= 1, `${card.id}: whenNotToUse empty`);
      assert.ok(card.inputContract.length > 10, `${card.id}: inputContract missing`);
      assert.ok(card.examples.length >= 1, `${card.id}: no example brief`);
    }
  });

  if (failures > 0) {
    console.error(`\n❌ check:agent-board-sync — ${failures} failure(s)`);
    process.exit(1);
  }
  console.log('\n✅ check:agent-board-sync — all assertions passed');
  process.exit(0);
}

main().catch((err) => { console.error('❌ crashed:', err); process.exit(1); });
