/**
 * Content Pack document tools — the contentAgent's incremental external memory,
 * cloned 1:1 from chef-document-tools.ts (Menu Book pattern).
 *
 * The Content Pack is a single Markdown file per content project with anchored,
 * idempotently-upsertable sections. The agent writes brief → research → strategy →
 * per-platform drafts → image briefs → distribution as the pipeline matures, so the
 * full state survives across turns and context compaction (analogous to the chef's
 * Menu Book). Unlike the Menu Book this is an INTERNAL working artifact (not a client
 * deliverable), so there is no PDF render — Markdown render is enough.
 */
import { createTool } from '@mastra/core/tools';
import { z } from 'zod';
import * as fs from 'fs/promises';
import * as path from 'path';
import { ContentService } from './content-service.js';
import { withDocumentLock } from '../../lib/document-write-lock.js';
import { getContentPacksDir } from '../../config/workspace-paths.js';

// ─── Content Pack directory configuration ─────────────────────────────────────
const CONTENT_DOCS_DIR = getContentPacksDir();

// Canonical Content Pack sections (order = order in the document).
const CANONICAL_SECTIONS = [
  'brief',
  'research',
  'strategy',
  'linkedin',
  'instagram',
  'tiktok',
  'image-briefs',
  'distribution',
] as const;
type SectionAnchor = typeof CANONICAL_SECTIONS[number];

const SECTION_TITLES: Record<SectionAnchor, string> = {
  brief: 'Brief',
  research: 'Research & Fresh Signals',
  strategy: 'Strategy & Editorial Plan',
  linkedin: 'LinkedIn',
  instagram: 'Instagram',
  tiktok: 'TikTok',
  'image-briefs': 'Image Briefs (prompts only)',
  distribution: 'Distribution & Schedule',
};

const SECTION_PLACEHOLDER = '_(to be filled)_';

// Anchor validation: canonical sections OR dynamic sub-sections like
// `linkedin:post-1`, `tiktok:hook-a`, `image-briefs:ig-carousel`.
const ANCHOR_PATTERN = /^[a-z][a-z0-9-]*(:[a-z0-9][a-z0-9-]*)?$/;

/** Human-readable title for any anchor (canonical or dynamic <type>:<slug>). */
function titleFor(anchor: string): string {
  if (anchor in SECTION_TITLES) return SECTION_TITLES[anchor as SectionAnchor];
  const [prefix, slug] = anchor.split(':');
  if (slug && prefix in SECTION_TITLES) {
    return `${SECTION_TITLES[prefix as SectionAnchor]}: ${slug.replace(/-/g, ' ')}`;
  }
  return anchor;
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

/** Returns a safe Content Pack file path for a project (path-traversal guard). */
function packPath(projectId: string): string {
  const safeId = projectId.replace(/[^a-zA-Z0-9_-]/g, '');
  if (!safeId) throw new Error('Invalid projectId.');
  const filePath = path.resolve(CONTENT_DOCS_DIR, `${safeId}.md`);
  if (!filePath.startsWith(CONTENT_DOCS_DIR + path.sep)) {
    throw new Error('Access denied: attempt to escape the Content Pack directory.');
  }
  return filePath;
}

function startMarker(anchor: string): string {
  return `<!-- section:${anchor} start -->`;
}
function endMarker(anchor: string): string {
  return `<!-- section:${anchor} end -->`;
}

/** Builds an empty Content Pack skeleton with anchored sections. */
function buildSkeleton(title: string, projectId: string): string {
  const lines: string[] = [];
  lines.push(`# 📣 Content Pack — ${title}`);
  lines.push('');
  lines.push(`<!-- content-pack projectId:${projectId} -->`);
  lines.push(`> Incrementally generated by contentAgent. Do not hand-edit content between markers.`);
  lines.push('');
  for (const anchor of CANONICAL_SECTIONS) {
    lines.push(`## ${SECTION_TITLES[anchor]}`);
    lines.push(startMarker(anchor));
    lines.push(SECTION_PLACEHOLDER);
    lines.push(endMarker(anchor));
    lines.push('');
  }
  return lines.join('\n');
}

/** Returns the current section body (between anchors) or '' if missing/placeholder. */
function getSectionBody(doc: string, anchor: string): string {
  const start = startMarker(anchor);
  const end = endMarker(anchor);
  const startIdx = doc.indexOf(start);
  const endIdx = doc.indexOf(end);
  if (startIdx === -1 || endIdx === -1 || endIdx < startIdx) return '';
  const body = doc.slice(startIdx + start.length, endIdx).trim();
  return body === SECTION_PLACEHOLDER ? '' : body;
}

/** Replaces a section's content in the document (idempotent upsert by anchor). */
/**
 * Strip section markers out of content before it is written.
 *
 * The markers are the document's structure, and `replaceSection` finds them with
 * `indexOf` — the FIRST occurrence. So content that itself contains a marker
 * splices a second one into the file, and every later write aims at the wrong
 * boundary. Observed live: an agent wrote a section whose body carried
 * `<!-- section:tiktok end -->`, and the pack ended up with two `image-briefs`
 * and two `distribution` sections. The visible damage is worse than the mess:
 * `content_doc_status` reads the FIRST `distribution` — the empty placeholder —
 * and reports the section missing while 1436 chars of it sit further down.
 *
 * Stripped rather than rejected: the content is real work, and losing it to
 * protect a comment marker would be the wrong trade.
 */
function stripSectionMarkers(content: string): string {
  return content.replace(/<!--\s*section:[a-z0-9:-]+\s+(?:start|end)\s*-->/gi, '').trimEnd();
}

function replaceSection(doc: string, anchor: string, content: string): string {
  const start = startMarker(anchor);
  const end = endMarker(anchor);
  content = stripSectionMarkers(content);
  const startIdx = doc.indexOf(start);
  const endIdx = doc.indexOf(end);
  if (startIdx === -1 || endIdx === -1 || endIdx < startIdx) {
    // Section doesn't exist (e.g. dynamic linkedin:post-1) — append at the end with a heading.
    return (
      doc.trimEnd() +
      `\n\n## ${titleFor(anchor)}\n${start}\n${content.trim()}\n${end}\n`
    );
  }
  const before = doc.slice(0, startIdx + start.length);
  const after = doc.slice(endIdx);
  return `${before}\n${content.trim()}\n${after}`;
}

/** Checks which canonical sections are filled (different from placeholder/empty). */
function sectionStatus(doc: string): { anchor: SectionAnchor; filled: boolean }[] {
  return CANONICAL_SECTIONS.map((anchor) => {
    const start = startMarker(anchor);
    const end = endMarker(anchor);
    const startIdx = doc.indexOf(start);
    const endIdx = doc.indexOf(end);
    let filled = false;
    if (startIdx !== -1 && endIdx !== -1 && endIdx > startIdx) {
      const body = doc.slice(startIdx + start.length, endIdx).trim();
      filled = body.length > 0 && body !== SECTION_PLACEHOLDER;
    }
    return { anchor, filled };
  });
}

// ─── Tools ───────────────────────────────────────────────────────────────────

export const contentDocumentInitTool = createTool({
  id: 'content_doc_init',
  description:
    'Creates the Content Pack (Markdown file) for a content project with empty, anchored sections (brief, research, strategy, linkedin, instagram, tiktok, image-briefs, distribution). Idempotent — if the file already exists, returns it without overwriting. Call once at the start of the project.',
  inputSchema: z.object({
    projectId: z.string().describe('Content project UUID'),
    title: z.string().optional().describe('Content Pack title (defaults to the project name from the DB)'),
  }),
  outputSchema: z.object({
    success: z.boolean(),
    path: z.string().optional(),
    created: z.boolean().optional().describe('true = newly created, false = already existed'),
    sections: z.array(z.string()).optional(),
    error: z.string().optional(),
  }),
  execute: async (context) => {
    try {
      await fs.mkdir(CONTENT_DOCS_DIR, { recursive: true });
      const filePath = packPath(context.projectId);

      // Idempotency — do not overwrite
      try {
        await fs.access(filePath);
        return {
          success: true,
          path: filePath,
          created: false,
          sections: [...CANONICAL_SECTIONS],
        };
      } catch {
        // doesn't exist — create it
      }

      let title = context.title;
      if (!title) {
        try {
          const content = new ContentService();
          const project = await content.getProject(context.projectId);
          title = project?.name || context.projectId;
        } catch {
          title = context.projectId;
        }
      }

      const skeleton = buildSkeleton(title, context.projectId);
      await fs.writeFile(filePath, skeleton, 'utf-8');
      return {
        success: true,
        path: filePath,
        created: true,
        sections: [...CANONICAL_SECTIONS],
      };
    } catch (err: any) {
      return { success: false, error: err.message };
    }
  },
});

export const contentDocumentWriteSectionTool = createTool({
  id: 'content_doc_write_section',
  description:
    'Writes or updates a single Content Pack section by its anchor. Idempotent — replaces the content between markers without duplicating. Call repeatedly as the pipeline matures. Canonical anchors: brief, research, strategy, linkedin, instagram, tiktok, image-briefs, distribution. Dynamic anchors: <canonical>:<slug> (e.g. linkedin:post-1, tiktok:hook-a, image-briefs:ig-carousel). Append mode adds to existing content instead of overwriting — use it to build a section incrementally (e.g. successive posts).',
  inputSchema: z.object({
    projectId: z.string().describe('Content project UUID'),
    anchor: z
      .string()
      .regex(
        ANCHOR_PATTERN,
        'Anchor must match the pattern: lowercase letters/digits/hyphens, optionally with a type prefix like linkedin: (e.g. linkedin:post-1).',
      )
      .describe(
        'Section anchor. Canonical: brief|research|strategy|linkedin|instagram|tiktok|image-briefs|distribution. Dynamic: <canonical>:<slug>.',
      ),
    content: z.string().describe('Section content (Markdown).'),
    mode: z
      .enum(['replace', 'append'])
      .optional()
      .default('replace')
      .describe(
        'replace = overwrite the whole section (default). append = add to existing content (for incremental building, e.g. successive posts).',
      ),
  }),
  outputSchema: z.object({
    success: z.boolean(),
    path: z.string().optional(),
    anchor: z.string().optional(),
    mode: z.string().optional(),
    error: z.string().optional(),
  }),
  execute: async (context) => {
    const filePath = packPath(context.projectId);
    // Read-modify-write on ONE file, called in parallel batches by the pipeline:
    // without serialization the batch members all read the same bytes and only
    // the last writer survives. See `withDocumentLock`.
    return withDocumentLock(filePath, async () => {
      try {
        let doc: string;
        try {
          doc = await fs.readFile(filePath, 'utf-8');
        } catch {
          return {
            success: false,
            error: `Content Pack for project ${context.projectId} does not exist — call content_doc_init.`,
          };
        }
        const mode = context.mode ?? 'replace';
        let nextContent = context.content;
        if (mode === 'append') {
          const existing = getSectionBody(doc, context.anchor);
          nextContent = existing
            ? `${existing}\n\n${context.content.trim()}`
            : context.content;
        }
        const updated = replaceSection(doc, context.anchor, nextContent);
        await fs.writeFile(filePath, updated, 'utf-8');
        return { success: true, path: filePath, anchor: context.anchor, mode };
      } catch (err: any) {
        return { success: false, error: err.message };
      }
    });
  },
});

export const contentDocumentStatusTool = createTool({
  id: 'content_doc_status',
  description:
    'Returns Content Pack progress: how many of the canonical sections are filled and which are missing. Use it to track completeness before moving to assemble/ship.',
  inputSchema: z.object({
    projectId: z.string().describe('Content project UUID'),
  }),
  outputSchema: z.object({
    success: z.boolean(),
    path: z.string().optional(),
    filled: z.number().optional(),
    total: z.number().optional(),
    sections: z
      .array(z.object({ anchor: z.string(), filled: z.boolean() }))
      .optional(),
    missing: z.array(z.string()).optional(),
    error: z.string().optional(),
  }),
  execute: async (context) => {
    try {
      const filePath = packPath(context.projectId);
      let doc: string;
      try {
        doc = await fs.readFile(filePath, 'utf-8');
      } catch {
        return {
          success: false,
          error: `Content Pack for project ${context.projectId} does not exist — call content_doc_init.`,
        };
      }
      const status = sectionStatus(doc);
      const filled = status.filter((s) => s.filled).length;
      return {
        success: true,
        path: filePath,
        filled,
        total: CANONICAL_SECTIONS.length,
        sections: status,
        missing: status.filter((s) => !s.filled).map((s) => s.anchor),
      };
    } catch (err: any) {
      return { success: false, error: err.message };
    }
  },
});

export const contentDocumentRenderTool = createTool({
  id: 'content_doc_render',
  description:
    'Returns the full current Content Pack content (the whole Markdown file) for preview, review, or assembly.',
  inputSchema: z.object({
    projectId: z.string().describe('Content project UUID'),
  }),
  outputSchema: z.object({
    success: z.boolean(),
    path: z.string().optional(),
    content: z.string().optional(),
    error: z.string().optional(),
  }),
  execute: async (context) => {
    try {
      const filePath = packPath(context.projectId);
      const content = await fs.readFile(filePath, 'utf-8');
      return { success: true, path: filePath, content };
    } catch (err: any) {
      return {
        success: false,
        error: `Cannot read the Content Pack for project ${context.projectId}: ${err.message}`,
      };
    }
  },
});

// Re-export helpers for potential downstream tooling.
export { packPath, replaceSection, CANONICAL_SECTIONS };
