/**
 * PR Body Builder (Etap 9.3)
 *
 * Generates structured, readable PR descriptions from
 * diagnostic plans, dispatch results, and review data.
 */

// ── Types ────────────────────────────────────────────────────────────────────

interface PRBodyInput {
  taskId: string;
  diagnosticPlan?: {
    rootCause?: string;
    hypothesis?: string;
    riskLevel?: string;
    subtasks?: Array<{
      id: string;
      type: string;
      description: string;
      targetFiles: string[];
    }>;
  };
  dispatchResult?: {
    groups?: Array<{
      groupIndex: number;
      subtasks: Array<{
        subtaskId: string;
        assignedModel: string;
        actualModel?: string;
        status: string;
        durationMs: number;
        filesChanged: string[];
        errors: string[];
        qualityAttempt?: number;
      }>;
      durationMs: number;
    }>;
    summary?: {
      totalSubtasks: number;
      succeeded: number;
      failed: number;
      skipped: number;
      needsHuman: number;
      conflictingFiles: string[];
      totalDurationMs: number;
      overallStatus: string;
    };
  };
  reviewVerdict?: string;
  reviewComments?: string;
  reviewIteration?: number;
  diffSummary?: string;
}

// ── Builder ──────────────────────────────────────────────────────────────────

/**
 * Build a structured PR body from task data.
 */
export function buildPRBody(input: PRBodyInput): string {
  const sections: string[] = [];

  // Header
  sections.push(`## 🤖 Auto-generated by Coding Agent\n`);
  sections.push(`> Task ID: \`${input.taskId}\``);
  sections.push('');

  // Root Cause
  if (input.diagnosticPlan?.rootCause) {
    sections.push(`### 🔍 Root Cause`);
    sections.push(input.diagnosticPlan.rootCause);
    if (input.diagnosticPlan.hypothesis) {
      sections.push(`\n**Hypothesis:** ${input.diagnosticPlan.hypothesis}`);
    }
    if (input.diagnosticPlan.riskLevel) {
      sections.push(`**Risk:** ${input.diagnosticPlan.riskLevel}`);
    }
    sections.push('');
  }

  // File Changes Table
  if (input.dispatchResult?.groups) {
    sections.push(`### 📁 Changes`);
    sections.push('');
    sections.push('| File | Subtask | Model | Status |');
    sections.push('|------|---------|-------|--------|');

    for (const group of input.dispatchResult.groups) {
      for (const subtask of group.subtasks) {
        const statusIcon = getStatusIcon(subtask.status);
        const model = subtask.actualModel
          ? `~~${formatModel(subtask.assignedModel)}~~ → ${formatModel(subtask.actualModel)}`
          : formatModel(subtask.assignedModel);
        const attempt = subtask.qualityAttempt && subtask.qualityAttempt > 1
          ? ` (attempt ${subtask.qualityAttempt})`
          : '';

        if (subtask.filesChanged.length > 0) {
          for (const file of subtask.filesChanged) {
            sections.push(`| \`${file}\` | ${subtask.subtaskId} | ${model} | ${statusIcon}${attempt} |`);
          }
        } else {
          sections.push(`| _(no files)_ | ${subtask.subtaskId} | ${model} | ${statusIcon}${attempt} |`);
        }
      }
    }
    sections.push('');
  }

  // Dispatch Summary
  if (input.dispatchResult?.summary) {
    const s = input.dispatchResult.summary;
    sections.push(`### 📊 Dispatch Summary`);
    sections.push('');
    sections.push(`- **Total:** ${s.totalSubtasks} subtasks | ✅ ${s.succeeded} succeeded | ❌ ${s.failed} failed | 🙋 ${s.needsHuman} needs_human | ⏭️ ${s.skipped} skipped`);
    sections.push(`- **Duration:** ${(s.totalDurationMs / 1000).toFixed(1)}s`);
    sections.push(`- **Overall:** ${s.overallStatus}`);

    if (s.conflictingFiles.length > 0) {
      sections.push(`- **⚠️ Conflicting files:** ${s.conflictingFiles.map((f) => `\`${f}\``).join(', ')}`);
    }

    // Collect unique models used
    const modelsUsed = new Map<string, number>();
    for (const group of input.dispatchResult.groups ?? []) {
      for (const st of group.subtasks) {
        const model = st.actualModel ?? st.assignedModel;
        modelsUsed.set(model, (modelsUsed.get(model) ?? 0) + 1);
      }
    }
    if (modelsUsed.size > 0) {
      const modelList = [...modelsUsed.entries()]
        .map(([m, count]) => `${formatModel(m)} (${count})`)
        .join(', ');
      sections.push(`- **Models:** ${modelList}`);
    }
    sections.push('');
  }

  // Review
  if (input.reviewVerdict) {
    const verdictIcon = input.reviewVerdict === 'approve' ? '✅' : input.reviewVerdict === 'block' ? '🚫' : '🔄';
    sections.push(`### 🔎 Code Review`);
    sections.push('');
    sections.push(`- **Verdict:** ${verdictIcon} ${input.reviewVerdict}`);
    if (input.reviewIteration) {
      sections.push(`- **Iteration:** ${input.reviewIteration}/3`);
    }
    sections.push(`- **Reviewer:** codeReviewAgent`);
    if (input.reviewComments) {
      sections.push(`\n<details><summary>Review comments</summary>\n\n${input.reviewComments}\n\n</details>`);
    }
    sections.push('');
  }

  // Quality Checks
  sections.push(`### ✅ Quality Checks`);
  sections.push('');

  const tscClean = !input.dispatchResult?.groups?.some((g) =>
    g.subtasks.some((s) => s.errors.some((e) => e.toLowerCase().includes('tsc'))),
  );
  const noSecrets = true; // Enforced by .gitignore + review
  const allTargetsTouched = input.dispatchResult?.summary
    ? input.dispatchResult.summary.succeeded === input.dispatchResult.summary.totalSubtasks
    : false;

  sections.push(`- [${tscClean ? 'x' : ' '}] TSC clean (0 errors)`);
  sections.push(`- [${noSecrets ? 'x' : ' '}] No hardcoded secrets`);
  sections.push(`- [${allTargetsTouched ? 'x' : ' '}] All target files touched`);
  sections.push('');

  // Footer
  sections.push('---');
  sections.push(`<sub>Generated by repo-maintenance-workflow at ${new Date().toISOString()}</sub>`);

  return sections.join('\n');
}

/**
 * Build a short PR title from task data.
 */
export function buildPRTitle(taskId: string, diagnosticPlan?: { rootCause?: string }): string {
  const prefix = taskId.startsWith('heal-') ? '🩹 auto-heal' : '🤖 agent';

  if (diagnosticPlan?.rootCause) {
    // Truncate root cause to fit in title
    const cause = diagnosticPlan.rootCause.substring(0, 60).replace(/\n/g, ' ');
    return `${prefix}: ${cause}`;
  }

  return `${prefix}: task ${taskId.substring(0, 8)}`;
}

/**
 * Build labels for the PR based on task characteristics.
 */
export function buildPRLabels(input: PRBodyInput): string[] {
  const labels: string[] = ['bot'];

  if (input.taskId.startsWith('heal-')) {
    labels.push('auto-heal');
  }

  // Add model tier labels
  if (input.dispatchResult?.groups) {
    const tiers = new Set<string>();
    for (const group of input.dispatchResult.groups) {
      for (const st of group.subtasks) {
        const model = st.actualModel ?? st.assignedModel;
        if (model.startsWith('ollama/')) tiers.add('local-model');
        else tiers.add('cloud-model');
      }
    }
    labels.push(...tiers);
  }

  // Risk level
  if (input.diagnosticPlan?.riskLevel === 'high') {
    labels.push('high-risk');
  }

  // Needs human
  if (input.dispatchResult?.summary?.needsHuman && input.dispatchResult.summary.needsHuman > 0) {
    labels.push('needs-human');
  }

  return labels;
}

// ── Helpers ──────────────────────────────────────────────────────────────────

function getStatusIcon(status: string): string {
  switch (status) {
    case 'success': return '✅';
    case 'partial': return '⚠️';
    case 'failed': return '❌';
    case 'needs_human': return '🙋';
    case 'skipped': return '⏭️';
    default: return '❓';
  }
}

function formatModel(modelId: string): string {
  // "ollama/qwen3:1.7b" → "qwen3:1.7b"
  // "google/gemini-2.5-pro" → "gemini-2.5-pro"
  return modelId.replace(/^(ollama|google|openai|anthropic)\//, '');
}
