/**
 * Hunt Report document tools — the huntAgent's incremental external memory, cloned from
 * content-document-tools.ts (Content Pack / Menu Book pattern).
 *
 * The Hunt Report is a single Markdown file per run with anchored, idempotently-upsertable
 * sections. The agent writes brief → discovery → per-lead detail → qualified/dropped tables →
 * drafts → review → summary as the pipeline matures, so a crash mid-run is recoverable and the
 * full state survives context compaction. Per-lead detail uses dynamic anchors `lead:<slug>`.
 *
 * This is an INTERNAL working/audit artifact (not a client deliverable) — Markdown only, no PDF.
 */
import { createTool } from '@mastra/core/tools';
import { z } from 'zod';
import * as fs from 'fs/promises';
import * as path from 'path';
import { HuntService } from './hunt-service.js';
import { withDocumentLock } from '../../lib/document-write-lock.js';
import { getHuntReportsDir } from '../../config/workspace-paths.js';

// ─── Hunt Report directory configuration ─────────────────────────────────────
const HUNT_DOCS_DIR = getHuntReportsDir();

// Canonical Hunt Report sections (order = order in the document).
const CANONICAL_SECTIONS = [
  'brief',
  'discovery',
  'qualified',
  'dropped',
  'drafts',
  'review',
  'summary',
] as const;
type SectionAnchor = typeof CANONICAL_SECTIONS[number];

const SECTION_TITLES: Record<SectionAnchor, string> = {
  brief: 'Brief',
  discovery: 'Discovery (candidates)',
  qualified: 'Qualified leads',
  dropped: 'Dropped (rejected / failed identity)',
  drafts: 'Cold-email drafts',
  review: 'Checkpoint review (human gate)',
  summary: 'Summary',
};

const SECTION_PLACEHOLDER = '_(to be filled)_';

// Anchor validation: canonical sections OR dynamic sub-sections like `lead:goat-cheese-co`.
const ANCHOR_PATTERN = /^[a-z][a-z0-9-]*(:[a-z0-9][a-z0-9-]*)?$/;

/** Human-readable title for any anchor (canonical or dynamic <type>:<slug>). */
function titleFor(anchor: string): string {
  if (anchor in SECTION_TITLES) return SECTION_TITLES[anchor as SectionAnchor];
  const [prefix, slug] = anchor.split(':');
  if (slug && prefix === 'lead') {
    return `Lead: ${slug.replace(/-/g, ' ')}`;
  }
  return anchor;
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

/** Returns a safe Hunt Report file path for a run (path-traversal guard). */
function reportPath(runId: string): string {
  const safeId = runId.replace(/[^a-zA-Z0-9_-]/g, '');
  if (!safeId) throw new Error('Invalid runId.');
  const filePath = path.resolve(HUNT_DOCS_DIR, `${safeId}.md`);
  if (!filePath.startsWith(HUNT_DOCS_DIR + path.sep)) {
    throw new Error('Access denied: attempt to escape the Hunt Report directory.');
  }
  return filePath;
}

function startMarker(anchor: string): string {
  return `<!-- section:${anchor} start -->`;
}
function endMarker(anchor: string): string {
  return `<!-- section:${anchor} end -->`;
}

/** Builds an empty Hunt Report skeleton with anchored sections. */
function buildSkeleton(title: string, runId: string): string {
  const lines: string[] = [];
  lines.push(`# 🎯 Hunt Report — ${title}`);
  lines.push('');
  lines.push(`<!-- hunt-report runId:${runId} -->`);
  lines.push(`> Incrementally generated by huntAgent. Do not hand-edit content between markers.`);
  lines.push('');
  for (const anchor of CANONICAL_SECTIONS) {
    lines.push(`## ${SECTION_TITLES[anchor]}`);
    lines.push(startMarker(anchor));
    lines.push(SECTION_PLACEHOLDER);
    lines.push(endMarker(anchor));
    lines.push('');
  }
  return lines.join('\n');
}

/** Returns the current section body (between anchors) or '' if missing/placeholder. */
function getSectionBody(doc: string, anchor: string): string {
  const start = startMarker(anchor);
  const end = endMarker(anchor);
  const startIdx = doc.indexOf(start);
  const endIdx = doc.indexOf(end);
  if (startIdx === -1 || endIdx === -1 || endIdx < startIdx) return '';
  const body = doc.slice(startIdx + start.length, endIdx).trim();
  return body === SECTION_PLACEHOLDER ? '' : body;
}

/** Replaces a section's content in the document (idempotent upsert by anchor). */
function replaceSection(doc: string, anchor: string, content: string): string {
  const start = startMarker(anchor);
  const end = endMarker(anchor);
  const startIdx = doc.indexOf(start);
  const endIdx = doc.indexOf(end);
  if (startIdx === -1 || endIdx === -1 || endIdx < startIdx) {
    // Section doesn't exist (e.g. dynamic lead:<slug>) — append at the end with a heading.
    return (
      doc.trimEnd() +
      `\n\n## ${titleFor(anchor)}\n${start}\n${content.trim()}\n${end}\n`
    );
  }
  const before = doc.slice(0, startIdx + start.length);
  const after = doc.slice(endIdx);
  return `${before}\n${content.trim()}\n${after}`;
}

/** Checks which canonical sections are filled (different from placeholder/empty). */
function sectionStatus(doc: string): { anchor: SectionAnchor; filled: boolean }[] {
  return CANONICAL_SECTIONS.map((anchor) => {
    const start = startMarker(anchor);
    const end = endMarker(anchor);
    const startIdx = doc.indexOf(start);
    const endIdx = doc.indexOf(end);
    let filled = false;
    if (startIdx !== -1 && endIdx !== -1 && endIdx > startIdx) {
      const body = doc.slice(startIdx + start.length, endIdx).trim();
      filled = body.length > 0 && body !== SECTION_PLACEHOLDER;
    }
    return { anchor, filled };
  });
}

// ─── Tools ───────────────────────────────────────────────────────────────────

export const huntDocumentInitTool = createTool({
  id: 'hunt_doc_init',
  description:
    'Creates the Hunt Report (Markdown file) for a run with empty, anchored sections (brief, discovery, ' +
    'qualified, dropped, drafts, review, summary). Idempotent — if the file already exists, returns it ' +
    'without overwriting. Call once at the start of a run, right after hunt_start_run.',
  inputSchema: z.object({
    runId: z.string().describe('Hunt run UUID.'),
    title: z.string().optional().describe('Hunt Report title (defaults to the run name from the DB).'),
  }),
  outputSchema: z.object({
    success: z.boolean(),
    path: z.string().optional(),
    created: z.boolean().optional().describe('true = newly created, false = already existed'),
    sections: z.array(z.string()).optional(),
    error: z.string().optional(),
  }),
  execute: async (context) => {
    try {
      await fs.mkdir(HUNT_DOCS_DIR, { recursive: true });
      const filePath = reportPath(context.runId);

      // Idempotency — do not overwrite
      try {
        await fs.access(filePath);
        return { success: true, path: filePath, created: false, sections: [...CANONICAL_SECTIONS] };
      } catch {
        // doesn't exist — create it
      }

      let title = context.title;
      if (!title) {
        try {
          const hunt = new HuntService();
          const run = await hunt.getRun(context.runId);
          title = run?.name || context.runId;
        } catch {
          title = context.runId;
        }
      }

      const skeleton = buildSkeleton(title, context.runId);
      await fs.writeFile(filePath, skeleton, 'utf-8');
      return { success: true, path: filePath, created: true, sections: [...CANONICAL_SECTIONS] };
    } catch (err: any) {
      return { success: false, error: err.message };
    }
  },
});

export const huntDocumentWriteSectionTool = createTool({
  id: 'hunt_doc_write_section',
  description:
    'Writes or updates a single Hunt Report section by its anchor. Idempotent — replaces the content ' +
    'between markers without duplicating. Call repeatedly as the pipeline matures. Canonical anchors: ' +
    'brief, discovery, qualified, dropped, drafts, review, summary. Dynamic anchors: lead:<slug> (e.g. ' +
    'lead:goat-cheese-co) for per-lead detail. Append mode adds to existing content instead of ' +
    'overwriting — use it to build a section incrementally (e.g. successive qualified leads).',
  inputSchema: z.object({
    runId: z.string().describe('Hunt run UUID.'),
    anchor: z
      .string()
      .regex(
        ANCHOR_PATTERN,
        'Anchor must match: lowercase letters/digits/hyphens, optionally with a type prefix like lead: (e.g. lead:goat-cheese-co).',
      )
      .describe('Section anchor. Canonical: brief|discovery|qualified|dropped|drafts|review|summary. Dynamic: lead:<slug>.'),
    content: z.string().describe('Section content (Markdown).'),
    mode: z
      .enum(['replace', 'append'])
      .optional()
      .default('replace')
      .describe('replace = overwrite the whole section (default). append = add to existing content (for incremental building).'),
  }),
  outputSchema: z.object({
    success: z.boolean(),
    path: z.string().optional(),
    anchor: z.string().optional(),
    mode: z.string().optional(),
    error: z.string().optional(),
  }),
  execute: async (context) => {
    const filePath = reportPath(context.runId);
    // Read-modify-write on ONE file, called in parallel batches by the pipeline:
    // without serialization the batch members all read the same bytes and only
    // the last writer survives. See `withDocumentLock`.
    return withDocumentLock(filePath, async () => {
      try {
        let doc: string;
        try {
          doc = await fs.readFile(filePath, 'utf-8');
        } catch {
          return { success: false, error: `Hunt Report for run ${context.runId} does not exist — call hunt_doc_init.` };
        }
        const mode = context.mode ?? 'replace';
        let nextContent = context.content;
        if (mode === 'append') {
          const existing = getSectionBody(doc, context.anchor);
          nextContent = existing ? `${existing}\n\n${context.content.trim()}` : context.content;
        }
        const updated = replaceSection(doc, context.anchor, nextContent);
        await fs.writeFile(filePath, updated, 'utf-8');
        return { success: true, path: filePath, anchor: context.anchor, mode };
      } catch (err: any) {
        return { success: false, error: err.message };
      }
    });
  },
});

export const huntDocumentStatusTool = createTool({
  id: 'hunt_doc_status',
  description:
    'Returns Hunt Report progress: how many of the canonical sections are filled and which are missing. ' +
    'Use it to track completeness before the checkpoint_review human gate.',
  inputSchema: z.object({
    runId: z.string().describe('Hunt run UUID.'),
  }),
  outputSchema: z.object({
    success: z.boolean(),
    path: z.string().optional(),
    filled: z.number().optional(),
    total: z.number().optional(),
    sections: z.array(z.object({ anchor: z.string(), filled: z.boolean() })).optional(),
    missing: z.array(z.string()).optional(),
    error: z.string().optional(),
  }),
  execute: async (context) => {
    try {
      const filePath = reportPath(context.runId);
      let doc: string;
      try {
        doc = await fs.readFile(filePath, 'utf-8');
      } catch {
        return { success: false, error: `Hunt Report for run ${context.runId} does not exist — call hunt_doc_init.` };
      }
      const status = sectionStatus(doc);
      const filled = status.filter((s) => s.filled).length;
      return {
        success: true,
        path: filePath,
        filled,
        total: CANONICAL_SECTIONS.length,
        sections: status,
        missing: status.filter((s) => !s.filled).map((s) => s.anchor),
      };
    } catch (err: any) {
      return { success: false, error: err.message };
    }
  },
});

export const huntDocumentRenderTool = createTool({
  id: 'hunt_doc_render',
  description:
    'Returns the full current Hunt Report content (the whole Markdown file) for preview at the ' +
    'checkpoint_review gate or for the final summary.',
  inputSchema: z.object({
    runId: z.string().describe('Hunt run UUID.'),
  }),
  outputSchema: z.object({
    success: z.boolean(),
    path: z.string().optional(),
    content: z.string().optional(),
    error: z.string().optional(),
  }),
  execute: async (context) => {
    try {
      const filePath = reportPath(context.runId);
      const content = await fs.readFile(filePath, 'utf-8');
      return { success: true, path: filePath, content };
    } catch (err: any) {
      return { success: false, error: `Cannot read the Hunt Report for run ${context.runId}: ${err.message}` };
    }
  },
});

export const huntDocumentTools = {
  huntDocumentInitTool,
  huntDocumentWriteSectionTool,
  huntDocumentStatusTool,
  huntDocumentRenderTool,
};

// Re-export helpers for potential downstream tooling.
export { reportPath, replaceSection, CANONICAL_SECTIONS };
